# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy

class ReportItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    title_translation = scrapy.Field()
    subtitle = scrapy.Field()
    subtitle_translation = scrapy.Field()
    abstract = scrapy.Field()
    abstract_translation = scrapy.Field()
    year = scrapy.Field()
    crawler_ip = scrapy.Field()
    volume = scrapy.Field()
    issue = scrapy.Field()
    url = scrapy.Field()
    organization = scrapy.Field()
    target = scrapy.Field()
    publish_time = scrapy.Field()
    init_time = scrapy.Field()
    update_time = scrapy.Field()
    journals_publisher = scrapy.Field()
    language = scrapy.Field()
    journals_title = scrapy.Field()
    journals_country = scrapy.Field()
    journals_issns = scrapy.Field()
    pages = scrapy.Field()
    term = scrapy.Field()
    term_code = scrapy.Field()
    keyword = scrapy.Field()
    keyword_translation = scrapy.Field()
    tags = scrapy.Field()
    author = scrapy.Field()
    author_affiliation = scrapy.Field()
    author_email = scrapy.Field()
    corporate_author = scrapy.Field()
    content_html = scrapy.Field()
    content = scrapy.Field()
    content_translation = scrapy.Field()
    identifier_type = scrapy.Field()
    identifier_id = scrapy.Field()
    file_urls = scrapy.Field()
    files = scrapy.Field()
    file_size = scrapy.Field()
    category = scrapy.Field()
    location = scrapy.Field()
    project = scrapy.Field()
    uuid = scrapy.Field()


class NewsItem(scrapy.Item):
    url = scrapy.Field()
    category = scrapy.Field()
    title = scrapy.Field()
    title_translation = scrapy.Field()
    subtitle = scrapy.Field()
    subtitle_translation = scrapy.Field()
    content = scrapy.Field()
    content_html = scrapy.Field()
    init_time = scrapy.Field()
    publish_time = scrapy.Field()
    update_time = scrapy.Field()
    abstract = scrapy.Field()
    abstract_translation = scrapy.Field()
    keyword = scrapy.Field()
    keyword_translation = scrapy.Field()
    author = scrapy.Field()
    area = scrapy.Field()
    target = scrapy.Field()
    source = scrapy.Field()
    domain = scrapy.Field()
    crawler_ip = scrapy.Field()
    language = scrapy.Field()
    location = scrapy.Field()
    project = scrapy.Field()
    uuid = scrapy.Field()

class PolicyItem(scrapy.Item):
    uuid = scrapy.Field()
    title = scrapy.Field()
    issued_number = scrapy.Field()
    publish_time = scrapy.Field()
    init_time = scrapy.Field()
    execute_time = scrapy.Field()
    cutoff_time = scrapy.Field()
    declaration_link = scrapy.Field()
    ministry_location = scrapy.Field()
    source = scrapy.Field()
    content = scrapy.Field()
    content_html = scrapy.Field()
    subject = scrapy.Field()
    type = scrapy.Field()
    industry_category = scrapy.Field()
    target = scrapy.Field()
    domain = scrapy.Field()
    crawler_ip = scrapy.Field()
    file_path = scrapy.Field()
    file_url = scrapy.Field()
    url = scrapy.Field()
    area = scrapy.Field()
    category = scrapy.Field()
    project = scrapy.Field()
    files = scrapy.Field()
    file_urls = scrapy.Field()